### ISSUE TITLE
Can you build this in OSX? I can not

### ISSUE THREAD

**Issue by blockcorporation** [rat4/blackcoin#39]
I can build bitcoin, peerunity, and others but for this project I can not build.

I get the following error

    ld: symbol(s) not found for architecture x86_64

I would think it is something to do with the code? Maybe we can fix this to make it easier to compile on OSX?

**Comment by blockcorporation** [comment]
Perhaps related to this?

https://github.com/Peerunity/Peerunity/issues/148

**Comment by crispybear** [comment]
I don't have a Mac machine to test with, however, I managed to have a community member to compile blackcoind using macports on his mac. 

    sudo port install boost db48 openssl miniupnpc
    git clone https://github.com/rat4/blackcoin/
    cd blackcoin/src
    make -f makefile.osx

**Comment by crispybear** [comment]
For compiling the QT wallet, appearently there is some bugs that affect bitcoin as well, https://trac.macports.org/ticket/46951

**Comment by blockcorporation** [comment]
Yes, I was able to compile the daemon but still unable to compile the -qt. Sorry I should have been more specific.

**Comment by crispybear** [comment]
According to the link I gave in privous comment, It seems that compiling the QT require [patching of *all* the boost headers](https://gist.githubusercontent.com/jkseppan/ccf72d14f8b0efee6c7d/raw/dc97fbeb6b086a44c75b857a0f31e7a4f2adcdda/scantailor-0.9.11.1-moc-boost.patch).

**Comment by crispybear** [comment]
Have you tried using homebrew instead of macports?

**Comment by blockcorporation** [comment]
Yeah I have tried with both. Fresh installs, etc. I believe it is a misconfigured -qt makefile file for mavericks.

**Comment by jprichardson** [comment]
Anymore luck with this? Tried on Yosemite at all? I may give it a shot on Yosemite/homebrew.

**Comment by nanocoinorg** [comment]
I had these issues and I made modifications to the *.pro file that has it compiling. Unfortunately now I see a runtime error:

    Assertion failed: (!pthread_mutex_lock(&m)), function lock, file /opt/local/include/boost/thread/pthread/recursive_mutex.hpp, line 110.
Abort trap: 6

It seems other projects have ran into this issue, once I solve it I can do a pull request.

**Comment by nanocoinorg** [comment]
Are the AssertLockHeld's in wallet.h and main.cpp required? Neither Litecoin or Reddcoin have them. Taking these out solve the mutex problem in mac, I was thinking of wrapping if statemnts to not include them in mac but I wanted a second opinion on this solution.

**Comment by nanocoinorg** [comment]
It appears they are for debugging but the fact that they are failing when turned on indicates a larger problem with the way locking is working.

**Comment by rat4** [comment]
By default AssertLockHeld() is a noop and therefore shouldn't matter.
A backtrace of the assertion fail might shed light on the problem.

**Comment by nanocoinorg** [comment]
I typically use linux so I'm still trying to find the best way to insert a backtrace to get information regarding the error.

**Comment by nanocoinorg** [comment]
I went through and commented out each AssertLockHeld and it didn't change anything so it is unrelated. Although I find it funny that Litecoin and Reddcoin both have simply removed the asserts considering the usefulness in debugging.

**Comment by nanocoinorg** [comment]
I have this fixed, it requires two minor changes to the .pro file. If you need me to build your newest OSX binary I can do this for you too.

**Comment by rat4** [comment]
That'd be great if you share the fix.

**Comment by mammix2** [comment]
Im having the same issues today, If you could share that fix for this error that would be great

'Assertion failed: (!pthread_mutex_lock(&m)), function lock, file /opt/local/include/boost/thread/pthread/recursive_mutex.hpp, line 110.'

**Comment by mammix2** [comment]
probably not ideal but adding NDEBUG to the .pro DEFINES allowed it to compile and run.

**Comment by rat4** [comment]
NDEBUG is too dangerous workaround, as it let wallet run despite the
unknown bug.

**Comment by mammix2** [comment]
Can you explain in more detail why it's too dangerous? 
Just for my knowledge i would like to understand. Thanks

**Comment by xranby** [comment]
mammix2: the assert is a runtime check to make sure that two simultaneously running threads of the program that manipulate a shared piece of information take turns by acquiring a lock before they alter the shared information. The assert has failed this means that data-corruption will occur if the two threads alters the shared piece of information at the same time.

If this kind of assert only triggers on OSX then the root cause of the issue may be in the Boost library’s or in the OSX posix thread handling.

**Comment by mammix2** [comment]
@xranby, thankyou very much. Very helpful info :)

**Comment by xranby** [comment]
FYI: blackcoin internally uses pthread_cond_wait and this function has been broken on Mac OS X
it is fixed in boost 1.57
http://www.boost.org/users/history/version_1_57_0.html

I would recommend you to try building blackcoin on OSX using at least boost 1.57

**Comment by mammix2** [comment]
@xranby, perfect, i'll give that a go

**Comment by mammix2** [comment]
unfortunately still getting the same error after updating boost. Updated ports and confirmed i'm now running version boost @1.57.0_1 

Any ideas?
do i need to change any boost suffix in the .pro file to specify 1.57 ?

**Comment by xranby** [comment]
can you attach a debugger like gdb or lldb and print a backtrace
(bt using gdb)
https://sourceware.org/gdb/onlinedocs/gdb/Backtrace.html
(thread backtrace when using lldb)
http://lldb.llvm.org/tutorial.html
when you hit the assert?

**Comment by mammix2** [comment]
Using LLDB within my Qt IDE, i think the first assert causing the error is in sync.h line 66
I'm far from being an expert at this stuff, could you confirm if this is correct?
Here is the full backtrace.
https://gist.github.com/mammix2/a8096aa3001bca71f42a

**Comment by rat4** [comment]
That looks like the static initialization order fiasco, and should be fixed by commit https://github.com/rat4/blackcoin/commit/7d766db4014403c4d1562da13247262a5c76e03a

**Comment by mammix2** [comment]
@rat4, well done buddy. that has sorted the problem :)
@xranby thanks for your help too.

**Comment by mammix2** [comment]
If you guys want an BC Mac wallet compiled let me know. I'll be glad to help :)

**Comment by crispybear** [comment]
From IRC:  < nscrypto> hey, when compiling on osx I get this error http://pastebin.com/j2uKgT6s

It was boost 1.58

**Comment by xranby** [comment]
The static_assert.hpp is clearly broken when boost has defined BOOST_NO_CXX11_STATIC_ASSERT

#ifndef BOOST_NO_CXX11_STATIC_ASSERT
#else
            // code here is in clearly the wrong order in boost 1.58
#endif

I will explain:

/opt/local/include/boost/static_assert.hpp:87:26: note: template is declared here
template <bool x> struct STATIC_ASSERTION_FAILURE;
                         ^

this line at 87 with the template definition has to be above the line 36 where the template is used:

/opt/local/include/boost/static_assert.hpp:36:48: note: expanded from macro 'BOOST_STATIC_ASSERT_MSG'
#     define BOOST_STATIC_ASSERT_MSG( B, Msg ) BOOST_STATIC_ASSERT( B )
                                               ^


Reorder the blocks and you have fixed boost.

**Comment by mrsmn** [comment]
@xranby Could you be more specific please? I didn't understand what I needed to modify in ```/opt/local/include/boost/static_assert.hpp``` so that this would work with ```boost 1.58```.

Thank you.

**Comment by rat4** [comment]
@mrsmn current git master should work with boost 1.58

**Comment by MystPhysX** [comment]
Thank you @rat4 

Other coins are experiencing this issue as well. I just wish this was higher up on the Google search results.

**Comment by mrsmn** [comment]
I actually found an easier fix that worked for me on OSX 10.9.5:
```
brew install boost --c++11
```
Cheers.

**Comment by mammix2** [comment]
@MystPhysX i forgot about this thread fixing that assert issue. Hope you get it sorted :)

**Comment by MystPhysX** [comment]
@mrsmn Thank you. I was not aware that Boost built without c++11 support by default, I'll have to keep that in mind in the future.

@mammix2 Cheers.

**Comment by knkrth** [comment]
Can any one one help me to fix.

`Assertion failed: (!pthread_mutex_lock(&m)), function lock, file /opt/local/include/boost/thread/pthread/recursive_mutex.hpp, line 110.`
